# Sereath's triggers
# Credits: suonho, yewbic, klankbeeld, Trebblofang, PatrickLieberkind, TheDweebMan
# More info in the credits.txt file

[universal]
	fade_in = "100"
    fade_out = "100"
	delay = "100"

# Menu
[p_cpa_415330]
    [p_cpa_415330.trigger]
        name = "menu"
[p_dad_396457]
    [p_dad_396457.trigger]
        name = "menu"
[p_dha_396471]
    [p_dha_396471.trigger]
        name = "menu"
[p_dupa_395388]
    [p_dupa_395388.trigger]
        name = "menu"

# Low HP
[s_sv_58962]
    [s_sv_58962.trigger]
        name = "lowhp"
        priority = "14"
        level = "30"
[t_p_173917]
    [t_p_173917.trigger]
        name = "lowhp"
        priority = "14"
        level = "30"

# Dead
[s_asmd_54921]
    [s_asmd_54921.trigger]
        name = "dead"
        priority = "15"
[t_ct_172641]
    [t_ct_172641.trigger]
        name = "dead"
        priority = "15"

# Void
[k_ha41h13022800_180964]
    [k_ha41h13022800_180964.trigger]
        name = "height"
        priority = "16"
        level = "-1"
        identifier = "inVoid"

# Dimension -1
[k_ha06_170329]
    [k_ha06_170329.trigger]
        name = "dimension"
        priority = "1"
        resource_name = "-1"
        identifier = "nether"
[k_ha09_170340]
    [k_ha09_170340.trigger]
        name = "dimension"
        identifier = "nether"
[k_ha10_133100]
    [k_ha10_133100.trigger]
        name = "dimension"
        identifier = "nether"
[k_ha11_133442]
    [k_ha11_133442.trigger]
        name = "dimension"
        identifier = "nether"
[k_ha33_174720]
    [k_ha33_174720.trigger]
        name = "dimension"
        identifier = "nether"
[k_ha74hk213915_213944]
    [k_ha74hk213915_213944.trigger]
        name = "dimension"
        identifier = "nether"
[k_ha3713012901_177862]
    [k_ha3713012901_177862.trigger]
        name = "dimension"
        identifier = "nether"
[k_ha3813020300_179029]
    [k_ha3813020300_179029.trigger]
        name = "dimension"
        identifier = "nether"
[k_hah_535963]
    [k_hah_535963.trigger]
        name = "dimension"
        identifier = "nether"
[k_hzha_126323]
    [k_hzha_126323.trigger]
        name = "dimension"
        identifier = "nether"
[k_kha01_170310]
    [k_kha01_170310.trigger]
        name = "dimension"
        identifier = "nether"
[t_cm_176930]
    [t_cm_176930.trigger]
        name = "dimension"
        identifier = "nether"
[t_hab_177830]
    [t_hab_177830.trigger]
        name = "dimension"
        identifier = "nether"
[t_sa_174359]
    [t_sa_174359.trigger]
        name = "dimension"
        identifier = "nether"

# Dimension 1
[k_ha14_135836]
    [k_ha14_135836.trigger]
        name = "dimension"
        priority = "1"
        resource_name = "1"
        identifier = "end"
[k_ha7212xcdq_13052514_212045]
    [k_ha7212xcdq_13052514_212045.trigger]
        name = "dimension"
        identifier = "end"
[t_hba_178607]
    [t_hba_178607.trigger]
        name = "dimension"
        identifier = "end"

# Dimension 10
[k_ha03_1703261112_534541]
    [k_ha03_1703261112_534541.trigger]
        name = "dimension"
        priority = "1"
        resource_name = "10"
        identifier = "beneath"
[k_ha04_170323]
    [k_ha04_170323.trigger]
        name = "dimension"
        identifier = "beneath"
[k_ha05_126250]
    [k_ha05_126250.trigger]
        name = "dimension"
        identifier = "beneath"
[k_ha17_170354]
    [k_ha17_170354.trigger]
        name = "dimension"
        identifier = "beneath"
[k_ha18_170368]
    [k_ha18_170368.trigger]
        name = "dimension"
        identifier = "beneath"
[k_ha19_170375]
    [k_ha19_170375.trigger]
        name = "dimension"
        identifier = "beneath"
[k_ha20_170387]
    [k_ha20_170387.trigger]
        name = "dimension"
        identifier = "beneath"
[k_ha21_170410]
    [k_ha21_170410.trigger]
        name = "dimension"
        identifier = "beneath"
[k_ha22_170460]
    [k_ha22_170460.trigger]
        name = "dimension"
        identifier = "beneath"
[k_ha40m172648_179845]
    [k_ha40m172648_179845.trigger]
        name = "dimension"
        identifier = "beneath"
[k_ha53smcd_193349]
    [k_ha53smcd_193349.trigger]
        name = "dimension"
        identifier = "beneath"
[k_ha57_178040_198477]
    [k_ha57_178040_198477.trigger]
        name = "dimension"
        identifier = "beneath"
[k_ha59_178040_198769]
    [k_ha59_178040_198769.trigger]
        name = "dimension"
        identifier = "beneath"
[k_ha62_13052513ww120bpm_201711]
    [k_ha62_13052513ww120bpm_201711.trigger]
        name = "dimension"
        identifier = "beneath"
[k_ha63_13052513ww_201837]
    [k_ha63_13052513ww_201837.trigger]
        name = "dimension"
        identifier = "beneath"
[k_ha68_13032100_205186]
    [k_ha68_13032100_205186.trigger]
        name = "dimension"
        identifier = "beneath"
[k_ha73_13052513_213146]
    [k_ha73_13052513_213146.trigger]
        name = "dimension"
        identifier = "beneath"
[k_ha60121369_200412]
    [k_ha60121369_200412.trigger]
        name = "dimension"
        identifier = "beneath"
[k_ha66185228_203571]
    [k_ha66185228_203571.trigger]
        name = "dimension"
        identifier = "beneath"
[k_ha011703261112_534204]
    [k_ha011703261112_534204.trigger]
        name = "dimension"
        identifier = "beneath"
[k_ha021703261112_534302]
    [k_ha021703261112_534302.trigger]
        name = "dimension"
        identifier = "beneath"
[k_hm01_121369_203085]
    [k_hm01_121369_203085.trigger]
        name = "dimension"
        identifier = "beneath"
[k_hm02_121369_203127]
    [k_hm02_121369_203127.trigger]
        name = "dimension"
        identifier = "beneath"
[k_hm03_121369_203184]
    [k_hm03_121369_203184.trigger]
        name = "dimension"
        identifier = "beneath"
[k_hm04_121369_203361]
    [k_hm04_121369_203361.trigger]
        name = "dimension"
        identifier = "beneath"
[k_hm011408040339_260132]
    [k_hm011408040339_260132.trigger]
        name = "dimension"
        identifier = "beneath"
[k_hprc0212030601_234122]
    [k_hprc0212030601_234122.trigger]
        name = "dimension"
        identifier = "beneath"
[k_htth_214011]
    [k_htth_214011.trigger]
        name = "dimension"
        identifier = "beneath"
[p_da_244961]
    [p_da_244961.trigger]
        name = "dimension"
        identifier = "beneath"
[t_hbsom_277193]
    [t_hbsom_277193.trigger]
        name = "dimension"
        identifier = "beneath"

# Bloodmoon
[k_ha42178043_182115]
    [k_ha42178043_182115.trigger]
        name = "bloodmoon"
        priority = "13"
[k_ha49182111_190687]
    [k_ha49182111_190687.trigger]
        name = "bloodmoon"
        priority = "13"
[k_hev1609250978_367197]
    [k_hev1609250978_367197.trigger]
        name = "bloodmoon"
        priority = "13"