# Please refer to the wiki page located at https://github.com/TheComputerizer/Music-Triggers/wiki
# or the discord server located at https://discord.gg/FZHXFYp8fc
# for any specific questions you might have regarding the main config file

[triggers]
	[triggers.dead]
		priority = "15"
	[triggers.lowhp]
		level = "25"
		priority = "14"
	[triggers.height]
		level = "-1"
		priority = "16"
		fade_in = "1"
		identifier = "inVoid"
	[[triggers.dimension]]
		priority = "1"
		resource_name = [ "424" ]
		identifier = "aurorian"
	[[triggers.dimension]]
		priority = "1"
		resource_name = [ "10" ]
		identifier = "beneath"
	[[triggers.dimension]]
		priority = "1"
		resource_name = [ "66" ]
		identifier = "erebus"
	[[triggers.dimension]]
		priority = "1"
		resource_name = [ "1" ]
		identifier = "end"
	[[triggers.dimension]]
		priority = "1"
		resource_name = [ "-1" ]
		identifier = "nether"
	[[triggers.dimension]]
		priority = "1"
		resource_name = [ "0" ]
		identifier = "overworld"
	[triggers.bloodmoon]
	[triggers.menu]
	[triggers.universal]
		fade_out = "100"
		persistence = "0"
		trigger_delay = "0"
		song_delay = "300:2100"
		start_delay = "0"
		stop_delay = "0"
		fade_in = "100"
[songs]
	[songs.p_sha_326085]
		triggers = [ "bloodmoon" ]
	[songs.k_hev1609250978_367197]
		triggers = [ "bloodmoon" ]
	[songs.k_ha49182111_190687]
		triggers = [ "bloodmoon" ]
	[songs.k_ha42178043_182115]
		triggers = [ "bloodmoon" ]
	[songs.t_se1_178113]
		triggers = [ "dimension-erebus" ]
	[songs.t_etmbl_277192]
		triggers = [ "dimension-erebus" ]
	[songs.nightbreak]
		triggers = [ "menu" ]
	[songs.gatheringdarkness]
		volume = "0.7"
		triggers = [ "dimension-erebus" ]
	[songs.k_ha71_13032200_211559]
		triggers = [ "dimension-erebus" ]
	[songs.k_ha31_173418]
		triggers = [ "dimension-erebus" ]
	[songs.k_bpdl_13090300_207930]
		triggers = [ "dimension-erebus" ]
	[songs.a5]
		triggers = [ "dimension-aurorian" ]
	[songs.a4]
		triggers = [ "dimension-aurorian" ]
	[songs.a3]
		triggers = [ "dimension-aurorian" ]
	[songs.a2]
		triggers = [ "dimension-aurorian" ]
	[songs.a1]
		triggers = [ "dimension-aurorian" ]
	[songs.t_hbsom_277193]
		triggers = [ "dimension-beneath" ]
	[songs.p_da_244961]
		triggers = [ "dimension-beneath" ]
	[songs.k_htth_214011]
		triggers = [ "dimension-beneath" ]
	[songs.k_hprc0212030601_234122]
		triggers = [ "dimension-beneath" ]
	[songs.k_hm011408040339_260132]
		triggers = [ "dimension-beneath" ]
	[songs.k_hm04_121369_203361]
		triggers = [ "dimension-beneath" ]
	[songs.k_hm03_121369_203184]
		triggers = [ "dimension-beneath" ]
	[songs.k_hm02_121369_203127]
		triggers = [ "dimension-beneath" ]
	[songs.k_hm01_121369_203085]
		triggers = [ "dimension-beneath" ]
	[songs.k_ha021703261112_534302]
		triggers = [ "dimension-beneath" ]
	[songs.k_ha011703261112_534204]
		triggers = [ "dimension-beneath" ]
	[songs.k_ha66185228_203571]
		triggers = [ "dimension-beneath" ]
	[songs.k_ha60121369_200412]
		triggers = [ "dimension-beneath" ]
	[songs.k_ha73_13052513_213146]
		triggers = [ "dimension-beneath" ]
	[songs.k_ha68_13032100_205186]
		triggers = [ "dimension-beneath" ]
	[songs.k_ha63_13052513ww_201837]
		triggers = [ "dimension-beneath" ]
	[songs.k_ha62_13052513ww120bpm_201711]
		triggers = [ "dimension-beneath" ]
	[songs.k_ha59_178040_198769]
		triggers = [ "dimension-beneath" ]
	[songs.k_ha57_178040_198477]
		triggers = [ "dimension-beneath" ]
	[songs.k_ha53smcd_193349]
		triggers = [ "dimension-beneath" ]
	[songs.k_ha40m172648_179845]
		triggers = [ "dimension-beneath" ]
	[songs.k_ha22_170460]
		triggers = [ "dimension-beneath" ]
	[songs.k_ha21_170410]
		triggers = [ "dimension-beneath" ]
	[songs.k_ha20_170387]
		triggers = [ "dimension-beneath" ]
	[songs.k_ha19_170375]
		triggers = [ "dimension-beneath" ]
	[songs.k_ha18_170368]
		triggers = [ "dimension-beneath" ]
	[songs.k_ha17_170354]
		triggers = [ "dimension-beneath" ]
	[songs.k_ha05_126250]
		triggers = [ "dimension-beneath" ]
	[songs.k_ha04_170323]
		triggers = [ "dimension-beneath" ]
	[songs.k_ha03_1703261112_534541]
		triggers = [ "dimension-beneath" ]
	[songs.k_ha41h13022800_180964]
		triggers = [ "height-inVoid" ]
	[songs.t_ct_172641]
		triggers = [ "dead" ]
	[songs.s_asmd_54921]
		triggers = [ "dead" ]
	[songs.t_p_173917]
		triggers = [ "lowhp" ]
	[songs.s_sv_58962]
		triggers = [ "lowhp" ]
	[songs.p_cpa_415330]
		triggers = [ "menu" ]
	[songs.p_dupa_395388]
		triggers = [ "menu" ]
	[songs.p_dha_396471]
		triggers = [ "menu" ]
	[songs.p_dad_396457]
		triggers = [ "menu" ]
	[songs.e1]
		triggers = [ "dimension-end" ]
	[songs.k_ha14_135836]
		triggers = [ "dimension-end" ]
	[songs.k_ha7212xcdq_13052514_212045]
		triggers = [ "dimension-end" ]
	[songs.t_hba_178607]
		triggers = [ "dimension-end" ]
	[songs.n4]
		triggers = [ "dimension-nether" ]
	[songs.n3]
		triggers = [ "dimension-nether" ]
	[songs.n2]
		triggers = [ "dimension-nether" ]
	[songs.n1]
		triggers = [ "dimension-nether" ]
	[songs.t_hab_177830]
		triggers = [ "dimension-nether" ]
	[songs.t_sa_174359]
		triggers = [ "dimension-nether" ]
	[songs.t_cm_176930]
		triggers = [ "dimension-nether" ]
	[songs.k_ha11_133442]
		triggers = [ "dimension-nether" ]
	[songs.k_ha10_133100]
		triggers = [ "dimension-nether" ]
	[songs.k_ha3813020300_179029]
		triggers = [ "dimension-nether" ]
	[songs.k_ha3713012901_177862]
		triggers = [ "dimension-nether" ]
	[songs.k_kha01_170310]
		triggers = [ "dimension-nether" ]
	[songs.k_ha09_170340]
		triggers = [ "dimension-nether" ]
	[songs.k_ha33_174720]
		triggers = [ "dimension-nether" ]
	[songs.k_ha06_170329]
		triggers = [ "dimension-nether" ]
	[songs.nb]
		triggers = [ "dimension-overworld" ]
	[songs.na]
		triggers = [ "dimension-overworld" ]
	[songs.h2]
		triggers = [ "dimension-overworld" ]
	[songs.cc]
		triggers = [ "dimension-overworld" ]
	[songs.c6]
		triggers = [ "dimension-overworld" ]
	[songs.c5]
		triggers = [ "dimension-overworld" ]
	[songs.c4]
		triggers = [ "dimension-overworld" ]
	[songs.c3]
		triggers = [ "dimension-overworld" ]
	[songs.c2]
		triggers = [ "dimension-overworld" ]
	[songs.c1]
		triggers = [ "dimension-overworld" ]
	[songs.universal]
